### ISSUE TITLE
pathlib is your friend

### ISSUE THREAD

**Issue by hughdbrown** [simonw/asgi-proxy-lib#4]
https://github.com/simonw/asgi-proxy-lib/blob/0730e872d5472db018f80a5c5b97aa80f03711ea/setup.py#L7-L12

```
from pathlib import Path

    return Path(__file__).absolute().parent.joinpath("README.md").read_text(encoding="utf8")
```

or:
```
    return Path(__file__).absolute().with_name("README.md").read_text(encoding="utf8")
```

or maybe one of:
```
    return Path(__file__).with_name("README.md").read_text(encoding="utf8")
```
```
    return Path("README.md").read_text(encoding="utf8")
```

I don't remember why the current directory is not known in `setup.py`.

**Comment by simonw** [comment]
I've been copy and pasting that block of code around for so long I forgot I never upgraded it to use `pathlib`!

I'm actually about to start switching over to `pyproject.toml` instead, which has a nicer mechanism for doing this. https://til.simonwillison.net/python/pyproject

With that I can just use:
```toml
[project]
name = "demo-package"
version = "0.1"
description = "This is a demo package"
readme = "README.md"
```
